### ISSUE TITLE
Switch to CefGlue

### ISSUE THREAD

**Issue by JakeGinnivan** [Code52/DownmarkerWPF#421]
https://bitbucket.org/xilium/xilium.cefglue/wiki/Home

Hopefully this will fix the rendering issues we have with the preview

**Comment by shiftkey** [comment]
Using #460 to get up to a more recent version of CefSharp. If someone still feels strongly about this, please reopen.

<img width="1001" alt="screen shot 2016-01-14 at 7 07 01 pm" src="https://cloud.githubusercontent.com/assets/359239/12318889/01499f54-baf2-11e5-8750-345f472776f2.png">
