### ISSUE TITLE
File type icon in %Temp% folder

### ISSUE THREAD

**Issue by charlesmilette** [Code52/DownmarkerWPF#446]
It is not a good idea to put the file type icon in the %Temp% folder, since some cleaning tools, like [CCleaner](https://www.piriform.com/ccleaner), will delete it when it cleans except if we add an exception. This will result in a ugly, broked image. Putting it in another place would be better (Something like %LocalAppData%\Markpad\markpadicon.ico)

**Comment by unlimitedtechworks** [comment]
I couldn't find the .ico in %temp%. I even ran CCleaner, and there was nothing wrong with the icons.

For the Windows App, the icon is stored at `C:\Program Files\WindowsApps\<markapp_folder>`

For the Windows Desktop App, the icon is stored at `C:\Users\<username>\AppData\Local\Apps\<markapp_folder>` Note `<markapp_folder>` is a bunch of gibberish.

**Comment by charlesmilette** [comment]
I mean for the file, the icon wich is displayed for an markdown file in explorer. If you delete temp files, the icon should be broken. Look at this registery entry wich determines the icon:`
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\markpad.md]

[HKEY_CURRENT_USER\Software\Classes\markpad.md\DefaultIcon]
@="C:\\Users\\Charles\\AppData\\Local\\Temp\\MarkPad.0.11.0.49\\markpaddoc.ico"

[HKEY_CURRENT_USER\Software\Classes\markpad.md\shell]

[HKEY_CURRENT_USER\Software\Classes\markpad.md\shell\open]

[HKEY_CURRENT_USER\Software\Classes\markpad.md\shell\open\command]
@="cmd /c \"\"C:\\Users\\Charles\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Code52\\MarkPad Nightly.appref-ms\" \"%1\"\""
`

This was taken whit the Nightly release

**Comment by unlimitedtechworks** [comment]
I installed a fresh nightly build v0.11.0.50 (I don't now where to get older versions). When I delete ~\MarkPad.0.11.0.50\markpaddoc.ico then start the app, the file gets recreated. So on my end the problem has nothing to do with the %temp% dir. However, I understand now the issue regarding the missing icon. In my fresh install, the icon was still missing.

**Comment by charlesmilette** [comment]
The %temp% dir gets cleaned up (remove all the content) by windows cleaning tool and other...
But when you have many git repos, ran CCleaner or anything other, and don't run MarkPad for a while, the icons get really eye-scorching. Take a look a the picture i've joined:
![capture](https://cloud.githubusercontent.com/assets/6440374/7032548/5c5c69e2-dd41-11e4-8467-62df8788707d.PNG)

**Comment by JakeGinnivan** [comment]
A pull request fixing this issue would be awesome :)

**Comment by charlesmilette** [comment]
Yeah, I'll try that, that should not be complicated.

**Comment by unlimitedtechworks** [comment]
My icon looks like
![image of icon](http://i.imgur.com/7D6l4tv.png)

Make sure it's not your OS. [Broken icons](http://www.virtualhelp.me/windows/782-broken-or-missing-icons-in-windows-78)

I'll leave this issue for now.

**Comment by charlesmilette** [comment]
Pull request has been accepted. If your icon is different, it's because you are on Windows 8, and me, I'm on Windows 7. But it is the same: the OS can't find the icon in the location MarkPad specified. Also, I don't know if the icons get replaced on new versions if it have changed.
