### ISSUE TITLE
Preview on HighDPI looks unreadable

### ISSUE THREAD

**Issue by xperiandri** [Code52/DownmarkerWPF#453]
Right panel which displays a preview looks unreadable on HighDPI when scaling is enabled (150% in my case)
<img width="810" alt="markpad highdpi" src="https://cloud.githubusercontent.com/assets/2365592/8881902/e8c7202a-324b-11e5-9cd3-9a9303727871.png">

**Comment by xperiandri** [comment]
Fix
https://github.com/cefsharp/CefSharp/issues/738

**Comment by boltomli** [comment]
Looks like it's OK now on the latest build. I'm on 200% scale.

**Comment by xperiandri** [comment]
Cool!
